version: '3'

services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile_node
    image: vue_img
    container_name: vue_container
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"